{{- if .Values.group.enabled -}}
kind: Group
apiVersion: user.openshift.io/v1
metadata:
  name: {{ .Values.dso.project}}-group-rw
  labels:
    app.kubernetes.io/managed-by: dso-console
users: {{ .Values.kibana.users | toYaml | nindent 2 }}
{{- end -}}