kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.logging.namespace}}-rw
  namespace: {{ .Values.logging.namespace}}
  labels:
    app.kubernetes.io/managed-by: dso-console
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: {{ .Values.dso.project}}-group-rw
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
