# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  labels:
    app.kubernetes.io/managed-by: dso-console
  name: datasource-am-{{ .Values.grafana.instanceName }}
  namespace: {{ .Values.grafana.namespace }}
spec:
  datasource:
    access: proxy
    basicAuth: true
    basicAuthUser: ${PROMETHEUS_USERNAME}
    isDefault: false
    jsonData:
      httpHeaderName1: X-Scope-OrgID
    name: Alertmanager
    secureJsonData:
      basicAuthPassword: ${PROMETHEUS_PASSWORD}
      httpHeaderValue1: {{ .Values.grafana.httpHeaderValue1 }}
    type: alertmanager
    uid: alertmanager
    url: {{ .Values.grafana.mimirUrl }}
  instanceSelector:
    matchLabels:
      app: {{ .Values.grafana.instanceName }}
  valuesFrom:
  - targetPath: basicAuthUser
    valueFrom:
      secretKeyRef:
        key: PROMETHEUS_USERNAME
        name: credentials
  - targetPath: secureJsonData.basicAuthPassword
    valueFrom:
      secretKeyRef:
        key: PROMETHEUS_PASSWORD
        name: credentials